export { default } from "./src/wallet-manager-multisig-safe.js";
export { default as WalletAccountMultisigSafe } from "./src/wallet-account-multisig-safe.js";
export type MultisigInfo = import("@tetherto/wdk-wallet/multisig").MultisigInfo;
export type MultisigProposal = import("@tetherto/wdk-wallet/multisig").MultisigProposal;
export type MultisigMessageProposal = import("@tetherto/wdk-wallet/multisig").MultisigMessageProposal;
export type MultisigTransactionOptions = import("@tetherto/wdk-wallet/multisig").MultisigTransactionOptions;
export type MultisigInteractionResult = import("@tetherto/wdk-wallet/multisig").MultisigInteractionResult;
export type MultisigSignature = import("@tetherto/wdk-wallet/multisig").MultisigSignature;
export type MultisigOptions = import("@tetherto/wdk-wallet/multisig").MultisigOptions;
export type FeeRates = import("@tetherto/wdk-wallet-evm").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet-evm").KeyPair;
export type EvmTransaction = import("@tetherto/wdk-wallet-evm").EvmTransaction;
export type TransactionResult = import("@tetherto/wdk-wallet-evm").TransactionResult;
export type EvmTransactionReceipt = import("@tetherto/wdk-wallet-evm").EvmTransactionReceipt;
export type TransferOptions = import("@tetherto/wdk-wallet-evm").TransferOptions;
export type ApproveOptions = import("@tetherto/wdk-wallet-evm").ApproveOptions;
export type ExistingSafeOptions = import("./src/wallet-account-read-only-multisig-safe.js").ExistingSafeOptions;
export type PredictedSafeOptions = import("./src/wallet-account-read-only-multisig-safe.js").PredictedSafeOptions;
export type UserOperationReceipt = import("./src/wallet-account-read-only-multisig-safe.js").UserOperationReceipt;
export type MultisigSafeOwnerAccount = import("./src/wallet-account-multisig-safe.js").MultisigSafeOwnerAccount;
export type MultisigSafeWalletCommonConfig = import("./src/wallet-account-read-only-multisig-safe.js").MultisigSafeWalletCommonConfig;
export type MultisigSafeWalletPaymasterTokenConfig = import("./src/wallet-account-read-only-multisig-safe.js").MultisigSafeWalletPaymasterTokenConfig;
export type MultisigSafeWalletSponsoredConfig = import("./src/wallet-account-read-only-multisig-safe.js").MultisigSafeWalletSponsoredConfig;
export type MultisigSafeWalletNativeCoinsConfig = import("./src/wallet-account-read-only-multisig-safe.js").MultisigSafeWalletNativeCoinsConfig;
export type MultisigSafeWalletConfig = import("./src/wallet-account-read-only-multisig-safe.js").MultisigSafeWalletConfig;
export type MultisigSafeWalletReadOnlyConfig = import("./src/wallet-account-read-only-multisig-safe.js").MultisigSafeWalletReadOnlyConfig;
export type MultisigCoordinatorProposal = import("./src/coordinators/index.js").MultisigCoordinatorProposal;
export type MultisigCoordinatorMessage = import("./src/coordinators/index.js").MultisigCoordinatorMessage;
export type MultisigCoordinatorMessageInput = import("./src/coordinators/index.js").MultisigCoordinatorMessageInput;
export type SafeTxServiceCoordinatorConfig = import("./src/coordinators/index.js").SafeTxServiceCoordinatorConfig;
export { default as WalletAccountReadOnlyMultisigSafe, DEFAULT_SAFE_MODULES_VERSION, DEFAULT_SAFE_VERSION } from "./src/wallet-account-read-only-multisig-safe.js";
export { IMultisigCoordinator, SafeTxServiceCoordinator, toJsonSafe } from "./src/coordinators/index.js";
export { ConfigurationError, HashMismatchError } from "./src/errors.js";
